name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ python3-dev

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build wheel setuptools
        python -m pip install numpy --no-build-isolation
        
    - name: Create package structure
      run: |
        # Create package directories
        mkdir -p tsds/utils
        touch tsds/utils/__init__.py
        mkdir -p build/lib.$(python -c "import distutils.util; print(distutils.util.get_platform())")-${{ matrix.python-version }}/utils
        
    - name: Build C++ extensions
      run: |
        for ext in trend skew kurtosis lb acf; do
          g++ -shared -fPIC \
            -I$(python -c "import numpy; print(numpy.get_include())") \
            -I$(python -c "import distutils.sysconfig; print(distutils.sysconfig.get_python_inc())") \
            src/${ext}.cpp \
            -o build/lib.$(python -c "import distutils.util; print(distutils.util.get_platform())")-${{ matrix.python-version }}/utils/${ext}$(python-config --extension-suffix) \
            -std=c++11
        done
        
    - name: Install package
      run: |
        cp -r build/lib.$(python -c "import distutils.util; print(distutils.util.get_platform())")-${{ matrix.python-version }}/utils/* tsds/utils/
        pip install -e .
        
    - name: Install test dependencies
      run: |
        pip install pytest pytest-cov pandas scipy statsmodels matplotlib scikit-learn
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) python -m pytest tests/ -v
